
CREATE DATABASE [VENDAS SUCOS] 
ON (NAME = VENDAS_SUCOS_DAT, FILENAME = 'F:\ARQUIVOS_SQL_SERVER\VENDAS_SUCOS.MDF', SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5)
LOG ON (NAME = VENDAS_SUCOS_LOG, FILENAME = 'F:\ARQUIVOS_SQL_SERVER\VENDAS_SUCOS.LDF', SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5);

