
CREATE TABLE [PRODUTOS]
(
	[CODIGO] NVARCHAR(10) NOT NULL,
	[DESCRITOR] NVARCHAR(100),
	[SABOR] NVARCHAR(50),
	[TAMANHO] NVARCHAR(50),
	[EMBALAGEM] NVARCHAR(50),
	[PREÇO LISTA] FLOAT,
	CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED ([CODIGO])
);

CREATE TABLE [VENDEDORES]
(
	[MATRICULA] NVARCHAR(5) NOT NULL,
	[NOME] NVARCHAR(100),
	[BAIRRO] NVARCHAR(50),
	[COMISSÃO] FLOAT,
	[DATA ADMISSÃO] DATE,
	[FÉRIAS] BIT,
	CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED ([MATRICULA])
);

-- EXERCICIO
CREATE TABLE [CLIENTES] 
(
	[CPF] NVARCHAR(11) NOT NULL,
	[NOME] NVARCHAR(100),
	[ENDEREÇO] NVARCHAR(150),
	[BAIRRO] NVARCHAR(50),
	[CIDADE] NVARCHAR(50),
	[ESTADO] NVARCHAR(50),
	[CEP] NVARCHAR(8),
	[DATA NASCIMENTO] DATE,
	[IDADE] TINYINT,
	[SEXO] NCHAR(1),
	[LIMITE CRÉDITO] FLOAT,
	[VOLUME COMPRA] FLOAT,
	[PRIMEIRA COMPRA] BIT,
	CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED ([CPF])
);