
ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_CLIENTES] FOREIGN KEY([CPF]) REFERENCES [CLIENTES] ([CPF]);

-- EXERCICIO
ALTER TABLE [NOTAS] WITH CHECK ADD CONSTRAINT [FK_NOTAS_VENDEDORES] FOREIGN KEY([MATRICULA]) REFERENCES [VENDEDORES] ([MATRICULA]);


