
SELECT * FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS];

INSERT INTO [PRODUTOS] 
	(CÓDIGO, DESCRITOR, EMBALAGEM, TAMANHO, SABOR, [PREÇO LISTA])
SELECT [CODIGO DO PRODUTO] AS CÓDIGO, [NOME DO PRODUTO] AS DESCRITOR, EMBALAGEM, TAMANHO, SABOR, [PREÇO DE LISTA] AS [PREÇO LISTA]
FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] <> '1040107';

-- EXERCICIO
SELECT * FROM CLIENTES;
SELECT * FROM [SUCOS_VENDAS].dbo.[TABELA DE CLIENTES];

INSERT INTO CLIENTES
	(CPF, NOME, ENDEREÇO, BAIRRO, CIDADE, ESTADO, CEP, [DATA NASCIMENTO], IDADE, SEXO,[LIMITE CRÉDITO], [VOLUME COMPRA], [PRIMEIRA COMPRA])
SELECT CPF, NOME, [ENDERECO 1] AS [ENDEREÇO], BAIRRO, CIDADE, ESTADO, CEP, [DATA DE NASCIMENTO] AS [DATA NASCIMENTO], IDADE, SEXO, [LIMITE DE CREDITO] AS [LIMITE CRÉDITO], [VOLUME DE COMPRA] AS [VOLUME COMPRA], [PRIMEIRA COMPRA]
FROM [SUCOS_VENDAS].dbo.[TABELA DE CLIENTES]
WHERE CPF NOT IN ('1471156710', '19290992743', '2600586709');