
SELECT * FROM [SUCOS_VENDAS].dbo.[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT * FROM [PRODUTOS] WHERE [CÓDIGO] = '1000889'

UPDATE [SUCOS_VENDAS].dbo.[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 7 WHERE [CODIGO DO PRODUTO] = '1000889'

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CÓDIGO], A.[PREÇO LISTA] 
FROM [SUCOS_VENDAS].dbo.[TABELA DE PRODUTOS] AS B
INNER JOIN [PRODUTOS] AS A ON A.CÓDIGO = B.[CODIGO DO PRODUTO]
WHERE A.CÓDIGO = '1000889'

UPDATE A SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA]
FROM [SUCOS_VENDAS].dbo.[TABELA DE PRODUTOS] AS B
INNER JOIN [PRODUTOS] AS A ON A.CÓDIGO = B.[CODIGO DO PRODUTO]
WHERE A.CÓDIGO = '1000889'