
SELECT * FROM SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1002334'

SELECT * FROM PRODUTOS WHERE [CÓDIGO] = '1002334'

SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CÓDIGO], A.[PREÇO LISTA] 
FROM SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] B INNER JOIN PRODUTOS A ON A.CÓDIGO = B.[CODIGO DO PRODUTO]
WHERE A.CÓDIGO = '1002334'

UPDATE SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 8
WHERE [CODIGO DO PRODUTO] = '1002334'

-- MERGE NECESSITA DE PONNTO VIRGULA
MERGE INTO [PRODUTOS] A
USING SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] B
ON A.CÓDIGO = B.[CODIGO DO PRODUTO] AND A.[CÓDIGO] = '1002334'
WHEN MATCHED THEN
UPDATE SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA];