
SELECT * FROM VENDEDORES

BEGIN TRANSACTION

	UPDATE VENDEDORES SET COMISSÃO = COMISSÃO * 1.15;

	INSERT INTO VENDEDORES ([MATRICULA], [NOME], [BAIRRO], [COMISSÃO], [DATA ADMISSÃO], [FÉRIAS])
	VALUES ('99999', 'JOÃO DA SILVA', 'ICARAÍ', 0.08, '2014-09-01', 0);

ROLLBACK TRANSACTION
COMMIT TRANSACTION