
-- SINTAXE TRIGGER

/*
CREATE TRIGGER <NOME DA TRIGGER>
ON <NOME DA TABELA>
[FOR/AFTER/INSTEAD OF][INSERT/UPDATE/DELETE]
AS
	<CORPO DA TRIGGER>
*/

/*
FOR = EXECUTA AO MESMO TEMPO QUE O COMANDO
AFTER = EXECUTA DEPOIS DO COMANDO
INSTEAD OF = EXECUTA NO LUGAR DO COMANDO
*/

CREATE TABLE TAB_FATURAMENTO
(
	DATA_VENDA DATE NULL,
	TOTAL_VENDA FLOAT
);

CREATE TRIGGER TG_ITENS_VENDIDOS
ON [ITENS VENDIDOS]
AFTER INSERT, UPDATE, DELETE
AS
	BEGIN
		DELETE FROM TAB_FATURAMENTO;
		INSERT INTO TAB_FATURAMENTO (DATA_VENDA, TOTAL_VENDA) 
			SELECT N.DATA AS DATA_VENDA, SUM(IV.QUANTIDADE * IV.[PREÇO]) AS TOTAL_VENDA
			FROM NOTAS AS N
			INNER JOIN [ITENS VENDIDOS] AS IV 
			ON IV.NÚMERO = N.NÚMERO
			GROUP BY N.DATA;
	END;

INSERT INTO NOTAS ([NÚMERO],[DATA],[CPF],[MATRICULA],[IMPOSTO]) VALUES ('0102', '2018-05-16', '1471156710', '235', 0.18);
INSERT INTO NOTAS ([NÚMERO],[DATA],[CPF],[MATRICULA],[IMPOSTO]) VALUES ('0100', '2018-05-15', '1471156710', '235', 0.18);
INSERT INTO [ITENS VENDIDOS] ([NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO]) VALUES ('0100', '1000889', 100, 5)
INSERT INTO [ITENS VENDIDOS] ([NÚMERO],[CÓDIGO],[QUANTIDADE],[PREÇO]) VALUES ('0102', '1002334', 100, 3.50);

DELETE FROM [ITENS VENDIDOS] WHERE NÚMERO = '0102' AND CÓDIGO = '1002334';

SELECT * FROM TAB_FATURAMENTO;