
CREATE DATABASE SUCOS_VENDAS_01;


-- DEFININDO PROPRIEDADES (TAMANHO MINIMO, TAMANHO MAXIMO, COMO CRESCE E DEFININDO O LOG DO SISTEMA)
CREATE DATABASE SUCOS_VENDAS
ON (NAME = SUCOS_VENDAS_DAT, FILENAME = 'C:\Users\rafae\OneDrive\ConfigSqlServer\SALES_VENDAS_02.MDF', SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5)
LOG ON (NAME = SUCOS_VENDAS_LOG, FILENAME = 'C:\Users\rafae\OneDrive\ConfigSqlServer\SALES_VENDAS_02.LDF', SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5);