
CREATE DATABASE SUCOS_VENDAS
ON (NAME = SUCOS_VENDAS_DATA, FILENAME = 'C:\Apps\ConfigSqlServer\SUCOS_VENDAS_DATA.MDF')
LOG ON (NAME = SUCOS_VENDAS_LOG, FILENAME = 'C:\Apps\ConfigSqlServer\SUCOS_VENDAS_LOG.LDF');

CREATE TABLE [TABELA DE CLIENTES]
(
	[CPF] NVARCHAR(11),
	[NOME COMPLETO] NVARCHAR(100),
	[ENDERECO 1] NVARCHAR(150),
	[ENDERECO 2] NVARCHAR(150),
	[BAIRRO] NVARCHAR(50),
	[CIDADE] NVARCHAR(50),
	[ESTADO] NCHAR(2),
	[CEP] NVARCHAR(8),
	[DATA DE NASCIMENTO] DATE,
	[IDADE] TINYINT,
	[SEXO] NCHAR(1),
	[LIMITE DE CREDITO] MONEY,
	[VOLUME DE COMPRA] FLOAT,
	[PRIMEIRA COMPRA] BIT
);