
INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES
('544931', 'Frescor de verão - 350ml - Limão', 'PET', '350ml', 'Limão', 3.20);

INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES
('1078680', 'Frescor de verão - 470ml - Manga', 'Lata', '470ml', 'Manga', 5.18);

-- Atualizando
UPDATE [TABELA DE PRODUTOS] SET [EMBALAGEM] = 'Lata', [PRECO DE LISTA] = 2.46 WHERE [CODIGO DO PRODUTO] = '544931';

UPDATE [TABELA DE PRODUTOS] SET [EMBALAGEM] = 'Garrafa' WHERE [CODIGO DO PRODUTO] = '1078680';