
INSERT INTO [TABELA DE PRODUTOS]
([CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PRECO DE LISTA])
VALUES
('788975', 'Pedaços de Frutas - 1,5 Litros - Maça', 'PET', '1,5 Litros', 'Maça', 18.01);


ALTER TABLE [TABELA DE PRODUTOS] ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY CLUSTERED ([CODIGO DO PRODUTO]);

ALTER TABLE [TABELA DE PRODUTOS] ALTER COLUMN [CODIGO DO PRODUTO] NVARCHAR(10) NOT NULL;