
CREATE TABLE [TABELA DE VENDEDORES]
(
	[MATRICULA] NVARCHAR(5),
	[NOME] NVARCHAR(100),
	[PERCENTUAL COMISSAO] FLOAT,
	[DATA ADMISSAO] DATE,
	[DE FERIAS] BIT
);

ALTER TABLE [TABELA DE VENDEDORES] ALTER COLUMN [MATRICULA] NVARCHAR(5) NOT NULL;

ALTER TABLE [TABELA DE VENDEDORES] ADD CONSTRAINT PK_VENDEDORES PRIMARY KEY CLUSTERED ([MATRICULA]);

INSERT INTO [TABELA DE VENDEDORES]([MATRICULA],[NOME],[PERCENTUAL COMISSAO],[DATA ADMISSAO],[DE FERIAS])
VALUES ('00235', 'Márcio Almeida Silva', 0.08, '2014-08-15', 0);

INSERT INTO [TABELA DE VENDEDORES]([MATRICULA],[NOME],[PERCENTUAL COMISSAO],[DATA ADMISSAO],[DE FERIAS])
VALUES ('00236', 'Cláudia Morais', 0.08, '2013-09-17', 1);

INSERT INTO [TABELA DE VENDEDORES]([MATRICULA],[NOME],[PERCENTUAL COMISSAO],[DATA ADMISSAO],[DE FERIAS])
VALUES ('00237', 'Roberta Martins', 0.11, '2017-03-18', 1);

INSERT INTO [TABELA DE VENDEDORES]([MATRICULA],[NOME],[PERCENTUAL COMISSAO],[DATA ADMISSAO],[DE FERIAS])
VALUES ('00238', 'Pericles Alves', 0.11, '2016-08-21', 0);