
SELECT * FROM [TABELA DE PRODUTOS];

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1000889';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Uva';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Limão';

-- EXERCICIO
SELECT * FROM [TABELA DE VENDEDORES] WHERE [NOME] = 'Cláudia Morais';