
SELECT * FROM [TABELA DE PRODUTOS] WHERE [EMBALAGEM] = 'PET';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] = 4.555;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] < 10;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] > 10;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <= 4.555;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] >= 4.555;

-- Maior ou igual com strings, é considerado o uso de ordem alfabetica
SELECT * FROM [TABELA DE PRODUTOS] WHERE [EMBALAGEM] >= 'Lata';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [EMBALAGEM] <= 'Lata';

-- Diferente
SELECT * FROM [TABELA DE PRODUTOS] WHERE [EMBALAGEM] <> 'Lata';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <> 4.555;

-- EXERCICIO
SELECT * FROM [TABELA DE VENDEDORES] WHERE [PERCENTUAL COMISSAO] > 0.10;