
SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga' OR [TAMANHO] = '700 ml';

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga' AND [TAMANHO] = '700 ml';

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT([SABOR] = 'Manga' AND [TAMANHO] = '700 ml');

SELECT * FROM [TABELA DE PRODUTOS] WHERE NOT([SABOR] = 'Manga' OR [TAMANHO] = '700 ml');

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga' AND NOT([TAMANHO] = '700 ml');

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] IN ('Manga', 'Laranja');

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] NOT IN ('Manga', 'Laranja');

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] > 10;

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] BETWEEN 10 AND 13;

-- EXERCICIO
SELECT *  FROM [ITENS NOTAS FISCAIS] 
WHERE [QUANTIDADE] > 60 AND [PREÇO] <= 3