

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS];

-- Irá retornar somente linhas com valores diferentes (não repetidos)
-- Ideal para verificar qualidades e caracteristicas dos dados
SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]; 

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Laranja'; 

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]; 

-- EXERCICIO
SELECT DISTINCT BAIRRO FROM [TABELA DE CLIENTES] WHERE ESTADO = 'RJ';