

-- Alguns exemplos que podem ser usados com GROUP BY: SUM, MAX, MIN, AVG, COUNT
-- Quando omitimos os campos de agregação será agregado para toda a tabela

SELECT * FROM [TABELA DE CLIENTES]; 

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO;

SELECT ESTADO, AVG([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO;

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM;

-- Contém ORDER BY implicito
SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE ESTADO = 'SP' GROUP BY BAIRRO;

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE ESTADO = 'SP' GROUP BY BAIRRO ORDER BY BAIRRO DESC;

-- Todos os campos do select precisam estar no GROUP BY
SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE ESTADO = 'SP' GROUP BY BAIRRO, ESTADO;

-- EXERCICIO
SELECT [CODIGO DO PRODUTO], MAX([QUANTIDADE]) AS [MAIOR VENDA] FROM [ITENS NOTAS FISCAIS] WHERE [CODIGO DO PRODUTO] = '1101035' GROUP BY [CODIGO DO PRODUTO];

SELECT COUNT(*) FROM [ITENS NOTAS FISCAIS] WHERE [CODIGO DO PRODUTO] = '1101035' AND QUANTIDADE = 99;

