
-- HAVING é uma condição (filtro) que se aplica ao resultado de uma agregação

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) AS [SOMA LIMITE] FROM [TABELA DE CLIENTES] WHERE ESTADO = 'SP' AND [SOMA LIMITE >= 140000] GROUP BY BAIRRO, ESTADO;

SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) AS [SOMA LIMITE] FROM [TABELA DE CLIENTES] WHERE ESTADO = 'SP' GROUP BY BAIRRO, ESTADO HAVING SUM([LIMITE DE CREDITO]) >= 140000;

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO;

SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO HAVING SUM([LIMITE DE CREDITO]) >= 850000;

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS [MÉDIA DE PREÇO], MAX([PREÇO DE LISTA]) AS [MAIOR PREÇO], MIN([PREÇO DE LISTA]) AS [MENOR PREÇO] FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS [MAIOR PREÇO], MIN([PREÇO DE LISTA]) AS [MENOR PREÇO] FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80;

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS [MAIOR PREÇO], MIN([PREÇO DE LISTA]) AS [MENOR PREÇO] FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80 AND MAX([PREÇO DE LISTA]) >= 6;

--EXERCICIO
SELECT CPF, COUNT(*) AS [QUANTIDADE DE COMPRAS] FROM [NOTAS FISCAIS] WHERE YEAR([DATA]) = 2016 GROUP BY CPF HAVING COUNT(*) > 2000;