
SELECT * FROM [TABELA DE PRODUTOS];

-- Fazemos um teste em um ou mais campos e, dependendo do resultado, teremos um ou outro valor
SELECT [NOME DO PRODUTO],
	CASE 
		WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'
	END
FROM [TABELA DE PRODUTOS];

SELECT [NOME DO PRODUTO],
	CASE 
		WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'
	END AS [FAIXA DE PREÇO], AVG([PREÇO DE LISTA]) AS [VALOR MÉDIO]
FROM [TABELA DE PRODUTOS] GROUP BY [NOME DO PRODUTO],
		CASE 
		WHEN [PREÇO DE LISTA] >= 12 THEN 'PRODUTO CARO'
		WHEN [PREÇO DE LISTA] >= 7 AND [PREÇO DE LISTA] < 12 THEN 'PRODUTO EM CONTA'
		ELSE 'PRODUTO BARATO'
	END;

--EXERCICIO
SELECT * FROM [TABELA DE CLIENTES];

SELECT NOME, [DATA DE NASCIMENTO],
	CASE
		WHEN YEAR([DATA DE NASCIMENTO]) < 1990 THEN 'ADULTO'
		WHEN YEAR([DATA DE NASCIMENTO]) BETWEEN 1990 AND 1995 THEN 'JOVEM'
		ELSE 'CRIANÇA'
	END AS [CLASSIFICAÇÃO DE FAIXA ETÁRIA]
FROM [TABELA DE CLIENTES];