
-- CAMPOS QUE SERÃO LIGADOS NÃO PRECISAM TER O MESMO NOME MAIS NECESSITAM SER DO MESMO TIPO, SENÃO É NECESSÁRIO REALIZAR CONVERSÃO DE TIPOS
-- NÃO É NECESSÁRIO CHAVE ESTRANGEIRA PARA LIGAR CAMPOS DE TABELAS, MAS É BOA PRÁTICA E A PERFORMANCE É BEM MENOR
-- INNER JOIN SÓ TRAS OS CAMPOS EM COMUM EM AMBAS AS TABELAS

SELECT * FROM [TABELA DE VENDEDORES];

SELECT * FROM [NOTAS FISCAIS];

SELECT * FROM [TABELA DE VENDEDORES] AS TV INNER JOIN [NOTAS FISCAIS] AS NF ON TV.MATRICULA = NF.MATRICULA; 

SELECT TV.MATRICULA, TV.NOME, COUNT(*) AS [NOTAS EMITIDAS] 
FROM [TABELA DE VENDEDORES] AS TV INNER JOIN [NOTAS FISCAIS] AS NF ON TV.MATRICULA = NF.MATRICULA 
GROUP BY TV.MATRICULA, TV.NOME; 

SELECT TV.MATRICULA, TV.NOME, YEAR([DATA]) AS ANO, COUNT(*) [QUANTIDADE DE NOTAS]
FROM [TABELA DE VENDEDORES] AS TV INNER JOIN [NOTAS FISCAIS] AS NF ON TV.MATRICULA = NF.MATRICULA 
GROUP BY TV.MATRICULA, TV.NOME, YEAR([DATA])
ORDER BY ANO, TV.NOME ASC; 

-- MANEIRA DA VELHA GUARDA
SELECT * FROM [TABELA DE VENDEDORES] AS TV INNER JOIN [NOTAS FISCAIS] AS NF ON TV.MATRICULA = NF.MATRICULA; 

SELECT * FROM [TABELA DE VENDEDORES] AS TV, [NOTAS FISCAIS] AS NF
WHERE TV.MATRICULA = NF.MATRICULA;

-- EXERCICIO
SELECT YEAR(NF.DATA) AS ANO, ROUND(SUM(INF.PREÇO * INF.QUANTIDADE), 2) AS FATURAMENTO
FROM [NOTAS FISCAIS] AS NF INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(NF.DATA);
