
SELECT * FROM [TABELA DE CLIENTES] INNER JOIN [NOTAS FISCAIS]
ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF;

SELECT [TABELA DE CLIENTES].NOME, COUNT(*) AS [QUANTIDADE DE NOTAS]
FROM [TABELA DE CLIENTES] INNER JOIN [NOTAS FISCAIS]
ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].NOME;

SELECT [TABELA DE CLIENTES].NOME, COUNT(*) AS [QUANTIDADE DE NOTAS]
FROM [TABELA DE CLIENTES] LEFT JOIN [NOTAS FISCAIS]
ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].NOME;

SELECT [TABELA DE CLIENTES].CPF, [TABELA DE CLIENTES].NOME, COUNT(*) AS [QUANTIDADE DE NOTAS]
FROM [TABELA DE CLIENTES] LEFT JOIN [NOTAS FISCAIS]
ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].CPF, [TABELA DE CLIENTES].NOME;