
-- FULL JOIN RETORNA TODOS OS REGISTROS DA TABELA
-- CROSS JOIN FAZ UMA ANALISE COMBINATORIA ENTRE TODOS OS REGISTROS

SELECT * FROM [TABELA DE VENDEDORES];
SELECT * FROM [TABELA DE CLIENTES];

SELECT TV.BAIRRO AS [BAIRRO DOS VENDEDORES], TC.BAIRRO AS [BAIRRO DOS CLIENTES]
FROM [TABELA DE VENDEDORES] AS TV
INNER JOIN [TABELA DE CLIENTES] AS TC
ON TV.BAIRRO = TC.BAIRRO; 

SELECT TV.BAIRRO AS [BAIRRO DOS VENDEDORES], ISNULL(TC.BAIRRO, 'VALOR NÃO CORRESPONDENTE') AS [BAIRRO DOS CLIENTES]
FROM [TABELA DE VENDEDORES] AS TV
LEFT JOIN [TABELA DE CLIENTES] AS TC
ON TV.BAIRRO = TC.BAIRRO; 

SELECT ISNULL(TV.BAIRRO, 'VALOR NÃO CORRESPONDENTE') AS [BAIRRO DOS VENDEDORES], TC.BAIRRO AS [BAIRRO DOS CLIENTES]
FROM [TABELA DE VENDEDORES] AS TV
RIGHT JOIN [TABELA DE CLIENTES] AS TC
ON TV.BAIRRO = TC.BAIRRO; 

SELECT ISNULL(TV.BAIRRO, 'NÃO EXISTE VENDEDOR NA ÁREA') AS [BAIRRO DOS VENDEDORES], ISNULL(TC.BAIRRO, 'NÃO EXISTE CLIENTES NA ÁREA') AS [BAIRRO DOS CLIENTES]
FROM [TABELA DE VENDEDORES] AS TV
FULL JOIN [TABELA DE CLIENTES] AS TC
ON TV.BAIRRO = TC.BAIRRO; 

SELECT TV.BAIRRO AS [BAIRRO DOS VENDEDORES], TC.BAIRRO AS [BAIRRO DOS CLIENTES]
FROM [TABELA DE VENDEDORES] AS TV
CROSS JOIN [TABELA DE CLIENTES] AS TC;