
SELECT * FROM [TABELA DE VENDEDORES];
SELECT * FROM [TABELA DE CLIENTES];

SELECT BAIRRO FROM [TABELA DE CLIENTES]
UNION
SELECT BAIRRO FROM [TABELA DE VENDEDORES];

SELECT BAIRRO FROM [TABELA DE CLIENTES]
UNION ALL
SELECT BAIRRO FROM [TABELA DE VENDEDORES];

-- VAI DAR ERRO, OS CAMPOS DEVEM SER DO MESMO TIPO
SELECT BAIRRO, [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]
UNION ALL
SELECT BAIRRO, NOME FROM [TABELA DE VENDEDORES];

SELECT BAIRRO, NOME, 'CLIENTE' FROM [TABELA DE CLIENTES]
UNION ALL
SELECT BAIRRO, NOME, 'VENDEDOR' FROM [TABELA DE VENDEDORES];