
SELECT NOME, BAIRRO FROM [TABELA DE VENDEDORES];

SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES] WHERE BAIRRO IN (SELECT BAIRRO FROM [TABELA DE VENDEDORES]);

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM;

SELECT NC.EMBALAGEM, NC.MAX_PRECO FROM (SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM) AS NC WHERE NC.MAX_PRECO <= 5;

--EXERCICIO
SELECT NF.CPF, NF.CONT FROM (SELECT CPF, COUNT(*) AS CONT FROM [NOTAS FISCAIS] WHERE YEAR([DATA]) = 2016 GROUP BY CPF) AS NF WHERE NF.CONT > 2000;