

SELECT NOME, BAIRRO FROM [TABELA DE VENDEDORES];

SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES] WHERE BAIRRO IN (SELECT BAIRRO FROM [TABELA DE VENDEDORES]);

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM;

SELECT NC.EMBALAGEM, NC.MAX_PRECO FROM (SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM) AS NC WHERE NC.MAX_PRECO <= 5;

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT * FROM VW_EMBALAGENS;

SELECT NC.EMBALAGEM, NC.MAX_PRECO AS [MENOR VALORES] FROM VW_EMBALAGENS AS NC WHERE NC.MAX_PRECO <= 5;
