
-- LTRIM TIRA ESPAÇOS EM BRANCO A ESQUERDA
-- RTRIM TIRA ESPAÇOS EM BRANCO A DIREITA
-- LEFT TIRA O NUMERO DE CARACTERES ESPECIFICADOS A ESQUERDA
-- RIGHT TIRA O NUMERO DE CARACTERES ESPECIFICADOS A ESQUERDA
-- CONCAT CRIA CONCATENAÇÕES ENTRE CAMPOS E CONSTANTES
-- SUBSTRING PEGA UM PEDAÇO DA STRING, RECEBE 3 PARAMETROS (EXPRESSION, START, LENGTH)
-- LEN RETORNA OS NUMEROS DE CARACTERES DA STRING 
-- UPPER TRANSFORMA PARA MAIUSCULAS
-- LOWER TRANSFORMA PARA MINUSCULAS
-- REPLACE TROCA UMA STRING POR OUTRA

SELECT LTRIM('                     OLÁ');

SELECT RTRIM('OLÁ                     ');

SELECT CONCAT('OLÁ, ', 'TUDO BEM?');

SELECT 'OLÁ, ' + 'TUDO BEM?';

SELECT LEFT('RUA AUGUSTA', 3);

SELECT RIGHT('RUA AUGUSTA', 7);

SELECT LOWER('RUA AUGUSTA');

SELECT UPPER('rua augusta');

SELECT REPLACE('R. AUGUSTA', 'R.', 'RUA');

SELECT SUBSTRING('RUA AUGUSTA',1,3)

SELECT LEN('RUA AUGUSTA');

SELECT * FROM [TABELA DE CLIENTES];

SELECT CONCAT(NOME,' (', CPF,') ') FROM [TABELA DE CLIENTES];

-- EXERCICIO
SELECT CONCAT(NOME,', ',[ENDERECO 1],', ',BAIRRO,', ',CIDADE,' - ',ESTADO) FROM [TABELA DE CLIENTES];