
-- TIME, DATE, SMALLDATE, DATETIME, DATETIME2, DATETIMEOFFSET
-- SYSDATETIME, SYSDATETIMEOFFSET, SYSUTCDATETIME FAZEM BASICAMENTE A MESMA COISA, MAS COM DIFERENÇA COM FUSO HORÁRIO
-- CURREN_TIMESTAMP
-- GETDATE
-- GETUTCDATE

-- DATENAME RETORNA UM STRING
-- DATEPART RETORNA INTEIRO
-- DAY RETORNA INTEIRO
-- MONTH RETORNA INTEIRO
-- YEAR RETORNA UM INTEIRO
-- ISDATE VERIFICA A POSSIBILIDADE DE DATA

SELECT SYSDATETIME();

SELECT SYSDATETIMEOFFSET();

SELECT SYSUTCDATETIME();

SELECT CURRENT_TIMESTAMP;

SELECT GETDATE();

SELECT GETUTCDATE();

SELECT DATENAME(YEAR,GETDATE());

SELECT DATENAME(MONTH,GETDATE());

SELECT DATENAME(WEEKDAY,GETDATE());

SELECT DATEPART(MONTH,GETDATE());

SELECT DAY(GETDATE());

SELECT YEAR(GETDATE());

SELECT DATEFROMPARTS(2021,05,15);

SELECT DATENAME(MONTH, DATEFROMPARTS(2021,05,15));

SELECT DATETIME2FROMPARTS(2021,5,15,15,43,120,58,9)

SELECT DATEDIFF(MONTH, DATEFROMPARTS(2020,05,15), GETDATE());

SELECT DATEADD(MONTH, 5, GETDATE());

SELECT ISDATE('2021-22-12');

SELECT ISDATE('2018-25-28');

SELECT [DATA], CONCAT(DATENAME(DAY, [DATA]), ' ', DATENAME(MONTH, [DATA]), ' ', DATENAME(YEAR, [DATA])) FROM [NOTAS FISCAIS];

--EXERCICIO
SELECT * FROM [TABELA DE CLIENTES];

SELECT NOME, DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE()) AS IDADE FROM [TABELA DE CLIENTES];