
-- CEILING RETORNA O MAIOR INTEIRO
-- FLOOR RETORNA O MENOR INTEIRO
-- RAND CRIA VALORES RANDOMICOS
-- ROUND ARREDONDA VALORES

SELECT CEILING(12.3332233);

SELECT FLOOR(12.33333);

SELECT RAND();

SELECT RAND(30);

SELECT ROUND(12.3332233, 2);

--EXERCICIO
SELECT YEAR(NF.DATA) AS ANO, FLOOR(SUM(NF.IMPOSTO * (QUANTIDADE * INF.PREÇO))) AS IMPOSTO
FROM [NOTAS FISCAIS] AS NF 
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY YEAR(NF.DATA);
