
-- CAST É PADRÃO SQL
-- CONVERT PERTENCE AO SQL SERVER

SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(decimal(10,5), 193.27);

SELECT 'O PREÇO DO PRODUTO ' + [NOME DO PRODUTO] + ' É ' + [PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS]

SELECT 'O PREÇO DO PRODUTO ' + [NOME DO PRODUTO] + ' É ' + CONVERT(VARCHAR, [PREÇO DE LISTA])
FROM [TABELA DE PRODUTOS]

--EXERCICIO
SELECT * FROM [TABELA DE CLIENTES];
SELECT * FROM [NOTAS FISCAIS];
SELECT * FROM [ITENS NOTAS FISCAIS];

SELECT CONCAT('O cliente ', TP.NOME, ' faturou ', CONVERT(decimal(15,2), SUM(INF.PREÇO * INF.QUANTIDADE)), ' no ano de ', CONVERT(VARCHAR, YEAR(NF.DATA)))
FROM [TABELA DE CLIENTES] AS TP
INNER JOIN [NOTAS FISCAIS] AS NF ON NF.CPF = TP.CPF
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY TP.NOME, YEAR(NF.DATA);