
SELECT * FROM [TABELA DE CLIENTES];
SELECT * FROM [ITENS NOTAS FISCAIS];
SELECT * FROM [NOTAS FISCAIS];

SELECT * FROM [NOTAS FISCAIS] AS NF
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO;

SELECT NF.CPF, MONTH(NF.DATA), YEAR(NF.DATA), INF.QUANTIDADE FROM [NOTAS FISCAIS] AS NF
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY NF.CPF, MONTH(NF.DATA), YEAR(NF.DATA), INF.QUANTIDADE;

SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7) AS [DATA CONVERTIDA], INF.QUANTIDADE FROM [NOTAS FISCAIS] AS NF
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO

SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7) AS [ANO_MES], SUM(INF.QUANTIDADE) AS [QUANTIDADE MES] FROM [NOTAS FISCAIS] AS NF
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7) 

SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7) AS [ANO_MES], SUM(INF.QUANTIDADE) AS [QUANTIDADE MES] FROM [NOTAS FISCAIS] AS NF
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7) 

SELECT TC.NOME, TC.[VOLUME DE COMPRA] FROM [TABELA DE CLIENTES] AS TC;

SELECT TC.NOME, CQ.ANO_MES, CQ.[QUANTIDADE MES], TC.[VOLUME DE COMPRA] FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7) AS [ANO_MES], SUM(INF.QUANTIDADE) AS [QUANTIDADE MES] FROM [NOTAS FISCAIS] AS NF
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7)) CQ
INNER JOIN  [TABELA DE CLIENTES] AS TC ON CQ.CPF = TC.CPF;

SELECT AUX1.NOME, AUX1.ANO_MES, AUX1.[QUANTIDADE MES],
	CASE WHEN AUX1.[QUANTIDADE MES] <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
		 WHEN AUX1.[QUANTIDADE MES] > AUX1.[VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA'
	END STATUS
FROM
(SELECT TC.NOME, CQ.ANO_MES, CQ.[QUANTIDADE MES], TC.[VOLUME DE COMPRA] FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7) AS [ANO_MES], SUM(INF.QUANTIDADE) AS [QUANTIDADE MES] FROM [NOTAS FISCAIS] AS NF
INNER JOIN [ITENS NOTAS FISCAIS] AS INF ON INF.NUMERO = NF.NUMERO
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120),1,7)) CQ
INNER JOIN  [TABELA DE CLIENTES] AS TC ON CQ.CPF = TC.CPF) AS AUX1
ORDER BY AUX1.NOME, AUX1.ANO_MES;

SELECT AUX1.NOME, AUX1.ANO_MES, AUX1.[VOLUME DE COMPRA], AUX1.QUANTIDADE_MES, 
CONVERT(DECIMAL(15,2), (1 - (AUX1.[VOLUME DE COMPRA]/AUX1.QUANTIDADE_MES)) * 100) AS VARIACAO, 
CASE WHEN AUX1.QUANTIDADE_MES <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VÁLIDA'
WHEN AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA] THEN 'VENDA INVÁLIDA'
END AS STATUS_VENDA
FROM 
(SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_MES  FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO 
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7)) CQ
INNER JOIN [TABELA DE CLIENTES] TC ON TC.CPF = CQ.CPF) AUX1
WHERE  AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA] 
ORDER BY AUX1.NOME, AUX1.ANO_MES